version: '3.7'
services:
  odfe-node1:
    build:
      context: .
      args:
        ELK_VERSION: ${ELK_VERSION}
        OPEN_DISTRO_VERSION: ${OPEN_DISTRO_VERSION}
    image: odfe:${OPEN_DISTRO_VERSION}
    container_name: odfe-node1
    environment:
      - node.name=odfe-node1
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - cluster.initial_master_nodes=odfe-node1
      - discovery.seed_hosts=odfe-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./odfe-data1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - odfe-net
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:${OPEN_DISTRO_VERSION}
    container_name: odfe-kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
    networks:
      - odfe-net
  metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:${ELK_VERSION}
    container_name: metricbeat-node
    networks:
      - odfe-net
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    environment:
      - ELASTICSEARCH_HOST=odfe-node1
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin

volumes:
  odfe-data1:

networks:
  odfe-net:
